"""empty message

Revision ID: a03cbe08aa8c
Revises: 
Create Date: 2020-05-24 11:32:50.399752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03cbe08aa8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salvar_busca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('url', sa.CLOB(), nullable=True),
    sa.Column('palavras', sa.CLOB(), nullable=True),
    sa.Column('palavras_c', sa.CLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salvar_busca')
    # ### end Alembic commands ###
